version = 5.6.0
archive_dir = /etc/letsencrypt/archive/resalloc.site
cert = /etc/letsencrypt/live/resalloc.site/cert.pem
privkey = /etc/letsencrypt/live/resalloc.site/privkey.pem
chain = /etc/letsencrypt/live/resalloc.site/chain.pem
fullchain = /etc/letsencrypt/live/resalloc.site/fullchain.pem
[renewalparams]
account = 13c45e045e039397799990b7c81ae4a3
authenticator = webroot
webroot_path = /var/www/certbot,
server = https://acme-v02.api.letsencrypt.org/directory
key_type = ecdsa
[[webroot_map]]
resalloc.site = /var/www/certbot
www.resalloc.site = /var/www/certbot
